---
title: "Wealth, Marriage and Sex Selection"
author: "Code Documentation"
date: "June 2017"
output: pdf_document
---

## Summary

The code for running the model-simulations and counter-factual policy simulations is written in MATLAB. The bootstrap samples were drawn using a simple python script. Global Optimization Toolbox in MATLAB was used to solve the model most accurately and avoid local minimas.

## Directories

* `bs_nw` : Unweighted bootstrap sampling results are stored in this directory.
* `bs_results` : Results of bootstrap sampling weighted by caste size are stored in this directory.
* `Figures` : All generated figures go to this directory
* `data` : All the data files with observed sex ratios in the census from different income classes, castes and age groups are sourced from this directory.

## Shell script files

All the `.sh` files are the ones which were used to run the estimation on the SIT cluster at Universitat Pompeu Fabra (UPF). These will have to be modified accordingly based on what cluster the code is being run on.

## MATLAB scripts description

* `solve_model.m` : Function that takes X, Y and the parameters and returns H(k*). It solves the model recursively starting from the topmost income class and returns the predicted amount of sex selection in each class for the given distribution of incomes and parameters.
* `solve_model_all.m` : The same function as `solve_model` when giving a money transfer to all families with girls. It takes the transfer amount as another parameter.
* `solve_model_dtax.m` : The same function as `solve_model` when putting a tax on the dowry. It takes the tax `theta` as another parameter.
* `solve_model_top.m` : The same function as `solve_model` when giving a money transfer to top 2 poorest income class families with girls.
* `solve_model_girls.m` : The same function as `solve_model` when giving a money transfer directly to the girls instead of the parents.


* `set_vin.m` : Function that solves the model and returns the difference in the outside option and utility of the boy's family for a given guess of the boy's family utility at the top.
* `set_vin_all.m` : The same function as `set_vin` when giving a money transfer to all families with girls. It takes the transfer amount as another parameter.
* `set_vin_dtax.m` : The same function as `set_vin` when putting a tax on the dowry. It takes the tax `theta` as another parameter.
* `set_vin_top.m` : The same function as `set_vin` when giving a money transfer to top 2 poorest income class families with girls.
* `set_vin_girls.m` : The same function as `set_vin` when giving a money transfer directly to the girls instead of the parents.

* `sex_simulation_v9.m` : This script takes as input or generates the data as desired. It then calls the relevant functions to solve the model for this data and given parameters to get the predicted outcomes from the model and generate all the required figures in the `Figures` folder.

* `my_psi.m` : Implementation of the `psi` function in the paper.
* `my_phi.m, my_phi_dtax.m, my_phi_girls.m`: Functions to calculate the utility of the girls family under the corresponding scenarios.

* `getdata.m` : Function to read in the required data in the appropriate format from the `data` folder.

* `hk_stderr.m` : Script to read in results from bootstrap and calculate the means and standard errors.

* `estimation.m` : Script to run the structural estimation using MultiStart solver from the Global Optimization Toolbox in MATLAB to search estimate values of the parameters `a` and `alpha` in a given domain.

* `est_all.m` : Function called by the script `estimation.m` to get the overall sum of squared errors across all castes.

* `bstrap.m, bstrap_nw.m` : Scripts to do the bootstrap which are called through the shell script when running the bootstrap on the SIT cluster.

## `.mat` Files

Results of estimation for different age-groups and income class specifications.